//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anotaciones.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materiales
    {
        public int idmaterial { get; set; }
        public Nullable<int> idcorrelativo { get; set; }
        public string idmatricula { get; set; }
        public string descripcion { get; set; }
        public Nullable<decimal> Stock_inventario { get; set; }
        public Nullable<int> idunidadmedida { get; set; }
        public Nullable<decimal> preciopromedio { get; set; }
        public Nullable<int> idmoneda { get; set; }
        public Nullable<decimal> stockminimo { get; set; }
        public bool flg_anulado { get; set; }
        public int Usu_creacion { get; set; }
        public Nullable<int> Usu_modificacion { get; set; }
        public System.DateTime Fec_Creacion { get; set; }
        public Nullable<System.DateTime> Fec_Modificacion { get; set; }
    
        public virtual Moneda Moneda { get; set; }
        public virtual UnidaMedida UnidaMedida { get; set; }
    }
}
