//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anotaciones.Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CobranzaEntities : DbContext
    {
        public CobranzaEntities()
            : base("name=CobranzaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Materiales> Materiales { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<Moneda> Moneda { get; set; }
        public virtual DbSet<UnidaMedida> UnidaMedida { get; set; }
    }
}
