//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anotaciones.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnidaMedida
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UnidaMedida()
        {
            this.Materiales = new HashSet<Materiales>();
        }
    
        public int idunidadmedida { get; set; }
        public Nullable<int> idcorrelativo { get; set; }
        public string Descripcion { get; set; }
        public string Abreviatura { get; set; }
        public Nullable<bool> flg_anulado { get; set; }
        public Nullable<int> usu_creacion { get; set; }
        public Nullable<int> usu_modificacion { get; set; }
        public Nullable<System.DateTime> fec_Creacion { get; set; }
        public Nullable<System.DateTime> fec_Modificacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Materiales> Materiales { get; set; }
    }
}
